apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
      - name: pgpool
        image: pgpool/pgpool:4.3.3
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
              key: password
        - name: PGPOOL_PASSWORD_ENCRYPTION_METHOD
          value: "scram-sha-256"
        - name: PGPOOL_ENABLE_POOL_PASSWD
          value: "true"
        - name: PGPOOL_SKIP_PASSWORD_ENCRYPTION
          value: "false"
        volumeMounts:
        - name: pgpool-config
          mountPath: /config
        #- name: pgpool-tls
        #  mountPath: /config/tls
        readinessProbe:
          exec:
            command: ["sh", "-c", "PGPASSWORD=$POSTGRES_PASSWORD psql -w -U $POSTGRES_USERNAME -c 'SELECT 1' -h localhost"]
          timeoutSeconds: 2
          periodSeconds: 5
      volumes:
      - name: pgpool-config
        configMap:
          name: pgpool-config
      # Configure your own TLS certificate.
      # If not set, Pgpool-II will automatically generate the TLS certificate if ssl = on.
      #- name: pgpool-tls
      #  secret:
      #    secretName: pgpool-tls
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool
spec:
  selector:
    app: pgpool
  ports:
  - name: pgpool-port
    protocol: TCP
    port: 5432
    targetPort: 5432
